### ISSUE TITLE
heroku app.json

### ISSUE THREAD

**Issue by gupta-vipin** [Ambro17/AmbroBot#5]
hey @Ambro17 , please add an app.json file so that it can be easily deployed to heroku .

**Comment by Ambro17** [comment]
I currently have deployed two bits on heroku but never heard of the app.json

Do you have an example or a link where I can learn what is that about?

Just a minimal procfile that is included in this repo was all I needed

**Comment by gupta-vipin** [comment]
As I am new to this, I dont know how to deploy bots on heroku. Somehow I was reading on heroku so I came to know about this app.json thing. Here is the link : 
https://devcenter.heroku.com/articles/app-json-schema

Or can you please help me in deploying this on heroku, I am unable to get any tutorials.

**Comment by Ambro17** [comment]
You can follow the instructions here 
https://medium.com/@mandywxm/deploying-a-python-telegram-bot-on-heroku-51cc27769bd7
If you have any doubts you can find me as @BoedoCrow on telegram.
