### ISSUE TITLE
Your codes don't work for the newer version of python-telegram-bot

### ISSUE THREAD

**Issue by 21470669** [Ambro17/AmbroBot#6]
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-12.0

**Comment by Ambro17** [comment]
True, to use it one should pin the telegram bot version to <12

**Comment by 21470669** [comment]
I have installed the latest python-telegram-bot>=13, how can I pin to version<12 and run this specific bot using the old version environment?  Thanks!

**Comment by Ambro17** [comment]
Change [this line](https://github.com/Ambro17/AmbroBot/blob/master/requirements.txt#L4) to `python-telegram-bot==11.1.0`
